
services:

  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    restart: always
    shm_size: 128mb
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432

  server:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db_data: